model_list:
  - model_name: MythoMist 7B
    litellm_params:
      model: gryphe/mythomist-7b
      api_key: os.environ/OR_API_KEY
      api_base: https://openrouter.ai/api/v1/chat/completions

litellm_settings:
  drop_params: True
  set_verbose: True

general_settings: 
  # master_key: sk-1234 # [OPTIONAL] Only use this if you to require all calls to contain this key (Authorization: Bearer sk-1234)
  # database_url: "postgresql://<user>:<password>@<host>:<port>/<dbname>" # [OPTIONAL] use for token-based auth to proxy

environment_variables:
  # settings for using redis caching
  # REDIS_HOST: redis-16337.c322.us-east-1-2.ec2.cloud.redislabs.com
  # REDIS_PORT: "16337"
  # REDIS_PASSWORD: 
